#!/usr/bin/env python
import sys
import json
import uuid
import time
import httplib
import optparse

def http_client(method, resource, args=None):
    header = {
        'X-SHEPHERD-APPNAME' : appname,
        'X-SHEPHERD-AUTHKEY' : appkey
    }

    try:
        conn = httplib.HTTPConnection(sys.argv[1], sys.argv[2])
        conn.request(method, resource, json.dumps(args), header)

        response = conn.getresponse()
        return response.status, response.reason, json.loads(response.read())
    except Exception as e:
        return 500, 'EXCEPTION', str(e)

appname = sys.argv[3]
appkey = sys.argv[4]
workercount = int(sys.argv[5])

guid = str(uuid.uuid4())

status = 500
while status != 200:
    status, reason, msg = http_client('PUT',
                                      '/workers/{0}/sheepdog'.format(appname),
                                      dict(data=dict(expected=workercount,
                                                     guid=guid,
                                                     appname=appname),
                                           workflow='sheepdog'))
    time.sleep(5)

for i in range(workercount):
    status = 500
    while status != 200:
        status, reason, msg = http_client('PUT',
                                          '/workers/{0}/sheep-{1}'.format(
                                              appname, i),
                                          dict(data=dict(worker=i,
                                                         count=workercount,
                                                         guid=guid,
                                                         appname=appname),
                                               workflow='sheep'))
        time.sleep(5)

while True:
    time.sleep(5)
    status, reason, result = http_client('GET',
                                         '/workers/%s/sheepdog' % (appname))

    if (status != 200) or ('NOT_FOUND' == result):
        continue

    print(result)

    if 'SLEEPING_FOR_SIGNAL_5' == result:
        http_client('POST',
                    '/messages/{0}/sheepdog'.format(appname),
                    dict(code='report'))

    if result in ['PASS', 'FAIL']:
        break
